version: '3.8'

services:
    php:
      image: php:8.1-fpm
      container_name: mdgabx-php
      restart: always
      volumes: 
        - ../src:/var/www


    nginx:
      image: nginx:1.19-alpine
      container_name: mdgabx-nginx
      restart: always
      ports:
        - "8000:80"
      volumes:
        - ../src:/var/www
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php