version: '3.8'

services:
    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: mdgabx-php
      restart: always
      volumes:
        - ../src:/var/www
      working_dir: /var/www

      # image: php:8.1-fpm
      # container_name: mdgabx-php
      # restart: always
      # volumes: 
      #   - ../src:/var/www


    nginx:
      image: nginx:1.19-alpine
      container_name: mdgabx-nginx
      restart: always
      ports:
        - "8000:80"
      volumes:
        - ./src:/var/www
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
    db:
      container_name: mdgabx-db
      image: mysql:8.0
      volumes:
        - ./storage/mysql:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3306:3306
    