services:
    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: mdgabx-php
      restart: always
      volumes:
        - ../../docker-basics:/var/www 
      working_dir: /var/www

    nginx:
      image: nginx:1.19-alpine
      container_name: mdgabx-nginx
      restart: always
      ports:
        - "8000:80"
      volumes:
        - ../../docker-basics:/var/www  # Same mount for Nginx
        - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
    db:
      container_name: mdgabx-db
      image: mysql:8.0
      volumes:
        - ./storage/mysql:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 3306:3306
    mailhog:
     container_name: mdgabx-mailhog
     image: mailhog/mailhog
     restart: always
     logging:
      driver: "none"
     ports:
      - "8025:8025"
      - "1025:1025"
    cron:
     container_name: mdgabx-cron
     build: ./cron
     volumes:
       - ../../docker-basics:/var/www
       - ./log/cron:/var/log/cron
    